In [1]:
# Imp libs:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Spliting data
from sklearn.model_selection import train_test_split,GridSearchCV

from statsmodels.stats.outliers_influence import variance_inflation_factor

# Removing warnings
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
# storing file locations in variables

file1 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\01_District_wise_crimes_committed_IPC_2001_2012.csv'
file2 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\02_01_District_wise_crimes_committed_against_SC_2001_2012.csv'
file3 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\02_District_wise_crimes_committed_against_ST_2001_2012.csv'
file4 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\03_District_wise_crimes_committed_against_children_2001_2012.csv'
file5 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\08_01_Juvenile_apprehended_state_IPC_2001_2010.csv'
file6 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\11_Property_stolen_and_recovered_nature_of_property_2001_2010.csv'
file7 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\13_Police_killed_or_injured_on_duty2001_2010.csv'
file8 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv'
file9 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\17_Crime_by_place_of_occurrence_2001_2012.csv'
file10 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\35_Human_rights_violation_by_police_2001_2010.csv'
file11 = r'E:\DS Course Related\Capstone Project\India_Crime - Copy\42_District_wise_crimes_committed_against_women_2001_2012.csv'

# reading datasets

df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)
df3  = pd.read_csv(file3)
df4 = pd.read_csv(file4)
df5 = pd.read_csv(file5)
df6 = pd.read_csv(file6)
df7 = pd.read_csv(file7)
df8 = pd.read_csv(file8)
df9 = pd.read_csv(file9)
df10 = pd.read_csv(file10)
df11 = pd.read_csv(file11)

# list of available dataframes

df_list = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11]


In [3]:
for i in df_list:
    print('Column names in dataframe:',i.columns,'\n')
    print('Number of columns: ', len(i.columns),'\n\n')

Column names in dataframe: Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object') 

Number of columns:  33 


Column names in dataframe: Index(['STATE/UT', 'DISTRICT', 'Year', 'Murder', 'Rape',
       'Kidnapping and Abdu

In [4]:
df1['YEAR'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [5]:
df2['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [6]:
df3['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [7]:
df4['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [8]:
df5['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
      dtype=int64)

In [9]:
df6['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
      dtype=int64)

In [10]:
df7['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
      dtype=int64)

In [11]:
df8['YEAR'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [12]:
df9['YEAR'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [13]:
df10['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
      dtype=int64)

In [14]:
df11['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

Phase 1:

Data Collection/preparation part.



Note: 

You can collect data from anywhere (wiki, google, etc) but mention the link from where data is being collected.

You can collect the data manually. It's NOT a web scraping task.

Data should be collected for the years mentioned in the files. (If you don't find proper data, make your best judgment and fill it, It's absolutely OK. Do not worry about data accuracy)



The population of each state.

Literacy Rate in each state

Area of each state

Collect any other data that helps with your analysis. There is no limitation for anything.

Create a new file and keep the above-collected data.

In [15]:
# Collected data:

# https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population

# https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area

# https://www.census2011.co.in/literacy.php

df_past_pop = pd.read_excel('E:\DS Course Related\Capstone Project\Phase 1 data collection\past population data.xlsx')
df_pop = pd.read_excel('E:\DS Course Related\Capstone Project\Phase 1 data collection\Population data.xlsx')
df_area = pd.read_excel('E:\DS Course Related\Capstone Project\Phase 1 data collection\State areas data.xlsx')
df_lit = pd.read_excel('E:\DS Course Related\Capstone Project\Phase 1 data collection\Literacy Rate data.xlsx')

# Population data

In [16]:
# Population in indian states for years 2001 to 2012

imp_df_pop = df_pop[[df_pop.columns[1],df_pop.columns[7],df_pop.columns[8]]].head()
imp_df_pop

State or Union Territory  Urban population  Percent urban
0              West Bengal          29093002         0.3187
1              Uttarakhand           3049338         0.3023
2            Uttar Pradesh          44495063         0.2227
3                  Tripura            961453         0.2617
4                Telangana          13608665         0.3888

In [17]:
imp_df_past_pop = df_past_pop[[df_past_pop.columns[1],df_past_pop.columns[7],df_past_pop.columns[8]]].head()
imp_df_past_pop

State or union territory  Population (2001 Census)[11]  \
0            Uttar Pradesh                   166053600.0   
1              Maharashtra                    96752500.0   
2                    Bihar                    82879910.0   
3              West Bengal                    80221300.0   
4           Madhya Pradesh                    60385090.0   

   Population (2011 Census)[11]  
0                     199581477  
1                     112372972  
2                     103804630  
3                      91347736  
4                      72597565

In [18]:
imp_df_past_pop['Per month increase in population'] = (imp_df_past_pop[imp_df_past_pop.columns[2]] - imp_df_past_pop[imp_df_past_pop.columns[1]])/12

imp_df_past_pop['pop in 2002'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 1 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2003'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 2 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2004'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 3 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2005'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 4 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2006'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 5 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2007'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 6 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2008'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 7 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2009'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 8 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2010'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 9 * imp_df_past_pop['Per month increase in population']
imp_df_past_pop['pop in 2011'] = imp_df_past_pop[imp_df_past_pop.columns[1]] + 10 * imp_df_past_pop['Per month increase in population']

imp_df_past_pop

State or union territory  Population (2001 Census)[11]  \
0            Uttar Pradesh                   166053600.0   
1              Maharashtra                    96752500.0   
2                    Bihar                    82879910.0   
3              West Bengal                    80221300.0   
4           Madhya Pradesh                    60385090.0   

   Population (2011 Census)[11]  Per month increase in population  \
0                     199581477                      2.793990e+06   
1                     112372972                      1.301706e+06   
2                     103804630                      1.743727e+06   
3                      91347736                      9.272030e+05   
4                      72597565                      1.017706e+06   

    pop in 2002   pop in 2003   pop in 2004   pop in 2005   pop in 2006  \
0  1.688476e+08  1.716416e+08  1.744356e+08  1.772296e+08  1.800235e+08   
1  9.805421e+07  9.935591e+07  1.006576e+08  1.019593e+08  1.032610e+08   
2  8.462364e+07  8.636736e+07  8.811109e+07  8.985482e+07  9.159854e+07   
3  8.114850e+07  8.207571e+07  8.300291e+07  8.393011e+07  8.485732e+07   
4  6.140280e+07  6.242050e+07  6.343821e+07  6.445592e+07  6.547362e+07   

   pop in 2007   pop in 2008   pop in 2009   pop in 2010   pop in 2011  
0  182817538.5  1.856115e+08  1.884055e+08  1.911995e+08  1.939935e+08  
1  104562736.0  1.058644e+08  1.071661e+08  1.084679e+08  1.097696e+08  
2   93342270.0  9.508600e+07  9.682972e+07  9.857345e+07  1.003172e+08  
3   85784518.0  8.671172e+07  8.763892e+07  8.856613e+07  8.949333e+07  
4   66491327.5  6.750903e+07  6.852674e+07  6.954445e+07  7.056215e+07

# Area data

In [19]:
df_area.head()

Rank State (S) / Union Territory (UT) Area (km2)    Region  \
0  1 (S1)                        Rajasthan     342239   Western   
1  2 (S2)                   Madhya Pradesh     308245   Central   
2  3 (S3)                      Maharashtra     307713   Western   
3  4 (S4)                    Uttar Pradesh     240928  Northern   
4  5 (S5)                          Gujarat     196024   Western   

   National share (%)      Note  
0               10.41       NaN  
1                9.38  [note 1]  
2                9.36       NaN  
3                7.33       NaN  
4                5.96       NaN

In [20]:
df_area_f = df_area[[df_area.columns[1],df_area.columns[2]]].head()
df_area_f

State (S) / Union Territory (UT) Area (km2)
0                        Rajasthan     342239
1                   Madhya Pradesh     308245
2                      Maharashtra     307713
3                    Uttar Pradesh     240928
4                          Gujarat     196024

# Literacy data

In [21]:
df_lit.head()

State/UT   1951   1961   1971   1981   1991   2001   2011
0        A&N islands   30.3  40.07  51.15  63.19  73.02  81.30  86.27
1     Andhra Pradesh      -  21.19  24.57  35.66  44.08  60.47  67.66
2  Arunachal Pradesh      -   7.13  11.29  25.55  41.59  54.34  66.95
3              Assam  18.53  32.95  33.94      -  52.89  63.25  73.45
4              Bihar  13.49  21.95  23.17  32.32  37.49  47.00  61.82

In [22]:
imp_df_lit = df_lit[[df_lit.columns[0],df_lit.columns[6],df_lit.columns[7]]]
imp_df_lit.head()

State/UT   2001   2011
0        A&N islands  81.30  86.27
1     Andhra Pradesh  60.47  67.66
2  Arunachal Pradesh  54.34  66.95
3              Assam  63.25  73.45
4              Bihar  47.00  61.82

In [23]:
imp_df_lit['Per month increase in literacy'] = (imp_df_lit[imp_df_lit.columns[2]] - imp_df_lit[imp_df_lit.columns[1]])/12

imp_df_lit['literacy in 2002'] = imp_df_lit[imp_df_lit.columns[1]] + 1 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2003'] = imp_df_lit[imp_df_lit.columns[1]] + 2 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2004'] = imp_df_lit[imp_df_lit.columns[1]] + 3 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2005'] = imp_df_lit[imp_df_lit.columns[1]] + 4 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2006'] = imp_df_lit[imp_df_lit.columns[1]] + 5 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2007'] = imp_df_lit[imp_df_lit.columns[1]] + 6 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2008'] = imp_df_lit[imp_df_lit.columns[1]] + 7 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2009'] = imp_df_lit[imp_df_lit.columns[1]] + 8 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2010'] = imp_df_lit[imp_df_lit.columns[1]] + 9 * imp_df_lit['Per month increase in literacy']
imp_df_lit['literacy in 2012'] = imp_df_lit[imp_df_lit.columns[1]] + 11 * imp_df_lit['Per month increase in literacy']

imp_df_lit.head()

State/UT   2001   2011  Per month increase in literacy  \
0        A&N islands  81.30  86.27                        0.414167   
1     Andhra Pradesh  60.47  67.66                        0.599167   
2  Arunachal Pradesh  54.34  66.95                        1.050833   
3              Assam  63.25  73.45                        0.850000   
4              Bihar  47.00  61.82                        1.235000   

   literacy in 2002  literacy in 2003  literacy in 2004  literacy in 2005  \
0         81.714167         82.128333           82.5425         82.956667   
1         61.069167         61.668333           62.2675         62.866667   
2         55.390833         56.441667           57.4925         58.543333   
3         64.100000         64.950000           65.8000         66.650000   
4         48.235000         49.470000           50.7050         51.940000   

   literacy in 2006  literacy in 2007  literacy in 2008  literacy in 2009  \
0         83.370833            83.785         84.199167         84.613333   
1         63.465833            64.065         64.664167         65.263333   
2         59.594167            60.645         61.695833         62.746667   
3         67.500000            68.350         69.200000         70.050000   
4         53.175000            54.410         55.645000         56.880000   

   literacy in 2010  literacy in 2012  
0           85.0275         85.855833  
1           65.8625         67.060833  
2           63.7975         65.899167  
3           70.9000         72.600000  
4           58.1150         60.585000

# Saving scrapped data

In [24]:
imp_df_lit.to_csv(r'E:\DS Course Related\Capstone Project\Phase 1 data collection\Interpolated or clean files\lit.csv')

df_area_f.to_csv(r'E:\DS Course Related\Capstone Project\Phase 1 data collection\Interpolated or clean files\area.csv')

imp_df_past_pop.to_csv(r'E:\DS Course Related\Capstone Project\Phase 1 data collection\Interpolated or clean files\pop.csv')